# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7f75bf8b5ddb242d69a8fd10216290e"
name = "rt-b2b-app"
application_url = "https://shopify-react-test-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/customers/update"

[access_scopes]
scopes = "read_customers,write_customers,write_app_proxy"

[auth]
redirect_urls = [
  "https://shopify-react-test-app-production.up.railway.app/auth/callback",
  "http://localhost:3000/auth/callback"
]

[app_proxy]
url = "https://shopify-react-test-app-production.up.railway.app/app-proxy"
subpath = "rt-auth"
prefix = "apps"
